/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AuthModal: typeof import('./components/AuthModal.vue')['default']
    CalendarPanel: typeof import('./components/CalendarPanel.vue')['default']
    MobileDrawer: typeof import('./components/MobileDrawer.vue')['default']
    ToolbarPanel: typeof import('./components/ToolbarPanel.vue')['default']
  }
}
